### ISSUE TITLE
chapter03 on M1 Macbook Pro

### ISSUE THREAD

**Issue by pieterv-icloud-com** [PacktPublishing/Cloud-Native-Observability#23]
No arm64 support?

```
no matching manifest for linux/arm64/v8 in the manifest list entries
```

**Comment by jiekun** [comment]
Those application image / Dockerfile looks fine. It's caused by `otel/opentelemetry-collector-contrib:0.42.0`. I think the author does it on purpose, to minimize the potential impact of the new version. You can edit the image to  `otel/opentelemetry-collector-contrib:0.43.0`  or above. 

After changing the contrib tag, js report won't work. you should be able to find trace like this:
```
python -> python -> go -> go -> java
```

with 0.42.0 it should be:
```
js -> python -> python -> go -> go -> java
```

**Comment by MilenaLee** [comment]
in docker-compose.yml, I add "platform: linux/amd64" on the image that makes problem ( for me, those are "jaeger" and "opentelemetry-collector") 
like this,
```
  jaeger:
    image: jaegertracing/all-in-one:latest
    platform: linux/amd64 << added line
    container_name: jaeger
    ports:
      - "16686:16686"
    networks:
      - cloud-native-observability
```
